default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_39600_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_39600_test

production:
  <<: *default
  database: protospace_39600_production
  username: protospace_39600
  password: <%= ENV["PROTOSPACE_39596_DATABASE_PASSWORD"] %>
